### ISSUE TITLE
Node 16 is deprecated for GitHub Actions

### ISSUE THREAD

**Issue by spkane** [actions-tools/yaml-outputs#26]
Using the current version (v2) of this action in GitHub workflows will result in a warning message from GitHub.

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions-tools/yaml-outputs@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

This is a helpful action, and it would be great to continue using it while keeping the workflow output clean and uncluttered with non-actionable messages.

**Comment by bcramer-c1** [comment]
Upgrading to Node 20 will need to happen by May 13, 2024. See [this announcement](ttps://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/). 

I have updated this repo to work with Node 20 and conform to the latest type-script GitHub Action Template covered under this PR #27. Hopefully the maintainers of this project will accept it.

**Comment by mknet3** [comment]
Merged! Thanks @spkane for opening the issue and thanks @bcramer-c1 for the contribution.
